apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

# docker run -d ngnix:1.14.2 --name ngnix -p 80:80 (is the equalvent command in docker)
# kubectl create -f pod.yml (createas a pod with ngnix) | 
# kubectl get pods
# kubectl get pods -o wide (more details)
# curl IP ()
# pod do not have Auto Healing and Auto scaling capabilities (Kind: Deployment can be used to overcome this challenge) 


