name: Tag with major
on:
 push:
   branches:
     - qademo
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
     with:
         fetch-depth: '0'
   - name: Generate Git Tag
     id: generate_tag
     run: |
       VERSION_PREFIX="v"
       VERSION_MINOR="0"
       VERSION_PATCH="0"
       UPDATE_MAJOR=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR}.*" --sort=-refname | head -n 1 | grep -oE '[0-9]+$')
       UPDATE_MAJOR=$((UPDATE_MAJOR + 1))
       NEW_TAG="${VERSION_PREFIX}${UPDATE_MAJOR}.${VERSION_MINOR}.${VERSION_MINOR}"
       echo "Generated new tag: $NEW_TAG"
       echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
   - name: Push Git Tag
     run: |
       git config user.name "GitHub Actions"
       git config user.email "github-actions@users.noreply.github.com"
       git tag $NEW_TAG
       git push origin $NEW_TAG
