ACR TAGGING WITH MAJOR:

name: DEV-ACR Build and Tag image

on:
  push:
    branches:
      - 'AL-1408'
  workflow_dispatch:

env:
  IMAGE_NAME: devcdrxacr/patient-services
jobs:
  build:
    runs-on: 'ubuntu-latest-m'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DEV_ACR_ENDPOINT }}
        username: ${{ secrets.DEV_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DEV_CONTAINER_REGISTRY_PASSWORD }}
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.DEV_ACR_CREDENTIALS }}
    
    - name: Generate Git Tag
      run: |
        VERSION_PREFIX="v"
        VERSION_MINOR="0"
        VERSION_PATCH="0"
        AzureRegistryName="devcdrxacr"
        RepositoryName="devcdrxacr/patient-services"
        UPDATE_MAJOR=$(az acr repository show-tags --name $AzureRegistryName --repository $RepositoryName  --orderby time_desc --output tsv | head -n 1 | grep -oE '[0-9]+$')
        UPDATE_MAJOR=$((UPDATE_MAJOR + 1))
        NEW_TAG="${VERSION_PREFIX}${UPDATE_MAJOR}.${VERSION_MINOR}.${VERSION_MINOR}"
        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push image to registry
      run: |
        docker build -t devcdrxacr.azurecr.io/${{ secrets.DEV_CONTAINER_REGISTRY_USERNAME }}/patient-services:${{ env.NEW_TAG }} .
        docker push --disable-content-trust devcdrxacr.azurecr.io/${{ secrets.DEV_CONTAINER_REGISTRY_USERNAME }}/patient-services:${{ env.NEW_TAG }}
